/* host_inference_reference.c -- Day 12 deliverable + Day 13 reference.
 *
 * Host-side C reference implementation of the gesture-recognition runtime that
 * will be deployed to STM32U5 (B-U585I-IOT02A). Models the exact loop the C
 * code on U5 must execute:
 *
 *   for each frame t in [0, T):
 *     1. push frame_t into network input (bound to logits_out + cache_out[N])
 *     2. ai_run(handle) [or equivalent INT8 invoke]
 *     3. copy cache_out[N] back to cache_in[N] (TSM streaming continuity)
 *     4. apply early-exit policy on logits_out -> EXIT_NOW or CONTINUE
 *
 * Early-exit policy (Day 12 chosen for U5 deployment):
 *   variant       = C1j
 *   strategy      = S1 (max-softmax > thresh)
 *   thresh        = 0.85
 *   min_exit_frame= 5    (force at least obs ratio 0.75 before considering exit)
 *
 * INT8-domain comparison (no FP32 softmax needed on MCU):
 *   - dequantize all 27 logits with output_scale + output_zp
 *   - compute softmax in FP32 (27-class softmax is fast even on Cortex-M33)
 *   - if max(softmax) > 0.85 -> EXIT
 *
 * Faster alternative (avoid FP32 softmax entirely):
 *   - find argmax over INT8 logits[0..26]
 *   - max_logit_int8 = logits[argmax]
 *   - compare max_logit_int8 to a precomputed INT8 threshold for "softmax > 0.85"
 *     in a 27-class distribution; this requires offline calibration of the
 *     threshold per-deployment. Empirically (Day 12 numbers): "max_softmax > 0.85"
 *     corresponds roughly to "max_logit_int8 > prev_max + 50" in many INT8 quants,
 *     but exact value must be tuned at deployment time.
 *
 * This reference uses the FP32-softmax path (clear, easy to debug). The
 * threshold-on-int8 path can be swapped in for tighter cycle budgets if profiling
 * shows softmax + exp() is too expensive.
 *
 * Build (host):
 *   gcc -std=c11 -O2 -Wall -o host_inference_reference host_inference_reference.c -lm
 *
 * Or with X-CUBE-AI integration (Day 13):
 *   (linked against st_ai_runtime + network.c/.h generated by stedgeai)
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define K_CLASSES         27
#define T_FRAMES          8

/* C1j architecture: 17 inverted-residual blocks; TSM sites at residual blocks
 * where stride==1 && in_ch==out_ch && in_ch % shift_div==0. Exact site count
 * is N_TSM_SITES below; values come from running tsm_mbv2_tf.py smoke test
 * for width_mult=0.5 n_blocks=17. Day 13 will re-confirm from
 * stedgeai generate output. */
#define N_TSM_SITES       11   /* expected for C1j; update from stedgeai gen */

/* Early-exit policy parameters (Day 12 choice) */
#define MIN_EXIT_FRAME    5     /* obs >= (5+1)/8 = 0.75 floor */
#define S1_THRESH         0.85f /* max-softmax threshold */

typedef struct {
    /* INT8 TFLite output quantization: real = (q - zero_point) * scale */
    float output_scale;
    int   output_zero_point;
    /* Frame counter (re-zeroed on each clip / gesture session start) */
    int   frame_idx;
    /* Cache buffers for N TSM sites (sized per-site by deployment). For host
     * reference we keep static-max buffers; on MCU these get sized at compile
     * time from stedgeai-generated network_data.h sizes. */
    int8_t *cache_buf[N_TSM_SITES];
    int     cache_size[N_TSM_SITES];
} runtime_ctx_t;

/* Stub for the network forward call. On U5 this maps to ai_run() from
 * X-CUBE-AI generated network.c, with cache_in[N] + frame_in tied to inputs
 * and logits_out + cache_out[N] tied to outputs.
 *
 * For host reference: caller is expected to override this with a TFLite
 * Interpreter invoke (see scripts/eval_int8.py for the analogous Python path).
 */
extern int run_network_step(
    runtime_ctx_t *ctx,
    const int8_t *frame_in,         /* (H*W,) -- int8 quantized frame */
    int8_t       *logits_out        /* (K_CLASSES,) -- int8 output */
);

/* Dequantize INT8 logits + numerically stable softmax. */
static void int8_logits_to_softmax(const int8_t *q_logits,
                                   float scale, int zp,
                                   float *out_probs)
{
    float fp_logits[K_CLASSES];
    float max_logit = -INFINITY;
    for (int i = 0; i < K_CLASSES; ++i) {
        fp_logits[i] = ((float)q_logits[i] - (float)zp) * scale;
        if (fp_logits[i] > max_logit) max_logit = fp_logits[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < K_CLASSES; ++i) {
        out_probs[i] = expf(fp_logits[i] - max_logit);
        sum += out_probs[i];
    }
    if (sum < 1e-9f) sum = 1e-9f;
    float inv = 1.0f / sum;
    for (int i = 0; i < K_CLASSES; ++i) out_probs[i] *= inv;
}

/* Returns 1 if S1 early-exit fires at this frame (caller still gets logits). */
static int early_exit_s1(const int8_t *q_logits,
                          float scale, int zp,
                          int frame_idx,
                          int *pred_class)
{
    float probs[K_CLASSES];
    int8_logits_to_softmax(q_logits, scale, zp, probs);
    /* Argmax + max prob */
    int argmax = 0;
    float max_p = probs[0];
    for (int i = 1; i < K_CLASSES; ++i) {
        if (probs[i] > max_p) { max_p = probs[i]; argmax = i; }
    }
    *pred_class = argmax;

    /* Floor: never exit before MIN_EXIT_FRAME */
    if (frame_idx < MIN_EXIT_FRAME) return 0;
    /* S1: max prob > thresh -> exit */
    if (max_p > S1_THRESH) return 1;
    return 0;
}

/* Public entry: process one clip frame-by-frame, exiting early when policy
 * fires. Caller passes the T frames in order; we return the predicted class
 * and the actual exit frame.
 */
int process_clip(runtime_ctx_t *ctx,
                 const int8_t *frames[T_FRAMES],
                 int *out_pred,
                 int *out_exit_frame)
{
    int8_t logits[K_CLASSES];
    /* Initialize cache buffers to zero on start of clip (cold-start TSM) */
    for (int s = 0; s < N_TSM_SITES; ++s) {
        memset(ctx->cache_buf[s], 0, ctx->cache_size[s]);
    }
    ctx->frame_idx = 0;
    *out_pred = -1;
    *out_exit_frame = T_FRAMES - 1;

    for (int t = 0; t < T_FRAMES; ++t) {
        ctx->frame_idx = t;
        int rc = run_network_step(ctx, frames[t], logits);
        if (rc != 0) return rc;

        int pred = -1;
        int do_exit = early_exit_s1(logits, ctx->output_scale, ctx->output_zero_point,
                                     t, &pred);
        if (do_exit) {
            *out_pred = pred;
            *out_exit_frame = t;
            return 0;
        }
        /* If we reach T-1 without exit, take last-frame prediction */
        if (t == T_FRAMES - 1) {
            *out_pred = pred;
            *out_exit_frame = t;
        }
    }
    return 0;
}

/* ---- Smoke test / host emulation main ---- */
#ifdef HOST_TEST
/* Minimal mock that always returns logits with class 5 dominant; verifies the
 * early-exit logic without a real network. */
int run_network_step(runtime_ctx_t *ctx, const int8_t *frame_in, int8_t *logits_out)
{
    (void)frame_in;
    memset(logits_out, -100, K_CLASSES);
    /* Make class 5 the dominant prediction starting from frame 4 */
    if (ctx->frame_idx >= 4) {
        logits_out[5] = 120;  /* large positive logit */
    }
    return 0;
}

int main(void) {
    /* Setup ctx with stub cache buffers and quant params */
    runtime_ctx_t ctx = {0};
    ctx.output_scale = 0.5833f;   /* matches C1j PTQ INT8 output scale */
    ctx.output_zero_point = 96;
    for (int s = 0; s < N_TSM_SITES; ++s) {
        ctx.cache_size[s] = 1024;
        ctx.cache_buf[s] = calloc(1, 1024);
    }
    /* Build T fake frames */
    int8_t frame_buf[64*64];
    memset(frame_buf, 0, sizeof(frame_buf));
    const int8_t *frames[T_FRAMES];
    for (int t = 0; t < T_FRAMES; ++t) frames[t] = frame_buf;

    int pred = -1, exit_frame = -1;
    int rc = process_clip(&ctx, frames, &pred, &exit_frame);
    printf("process_clip rc=%d  pred=%d  exit_frame=%d  obs_ratio=%.3f\n",
           rc, pred, exit_frame, (float)(exit_frame + 1) / T_FRAMES);
    /* Expected: pred=5 (mock favors class 5 from frame 4), but MIN_EXIT_FRAME=5
     * so first eligible exit is frame 5. */

    for (int s = 0; s < N_TSM_SITES; ++s) free(ctx.cache_buf[s]);
    return 0;
}
#endif
