#ifndef EARLY_EXIT_POLICY_H_
#define EARLY_EXIT_POLICY_H_

#include <stdint.h>

#define EARLY_EXIT_PREFIX_COUNT 2
#define EARLY_EXIT_CLASS_COUNT 27
#define EARLY_EXIT_DISABLED_THRESHOLD 0xffffu

static const int early_exit_prefixes[EARLY_EXIT_PREFIX_COUNT] = { 8, 10 };

/*
 * Q15 softmax thresholds generated from the min_precision=0.90 policy for
 * the currently deployable jestermotion12_qat model.
 * A disabled class is set above the maximum q15 softmax value, so it never
 * accepts early.
 */
static const uint16_t early_exit_thresholds[EARLY_EXIT_PREFIX_COUNT][EARLY_EXIT_CLASS_COUNT] = {
    {
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD, 29491,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, 24576, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD, 13107,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
    },
    {
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, 31130, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, 26214, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD, EARLY_EXIT_DISABLED_THRESHOLD,
        EARLY_EXIT_DISABLED_THRESHOLD,
    },
};

static inline uint16_t early_exit_threshold_for(int prefix, int class_id)
{
    for (int i = 0; i < EARLY_EXIT_PREFIX_COUNT; i++) {
        if (early_exit_prefixes[i] == prefix) {
            return early_exit_thresholds[i][class_id];
        }
    }

    return EARLY_EXIT_DISABLED_THRESHOLD;
}

#endif // EARLY_EXIT_POLICY_H_
