"""Day 8 TSM deployment-path probe.

Builds a minimal "streaming student" with the exact A.streaming interface
the Plan requires:
    inputs:  frame_t [1, 1, H, W, 1], cache_0 [1, 1, H', W', n_shift_0], cache_1 [1, 1, H'', W'', n_shift_1]
    outputs: logits_t [1, 27], cache_0_out, cache_1_out

Then runs three checks:

  Check 1 (Quantization):  Convert FP32 -> INT8 TFLite via tfmot post-training
                            quantization. Compare FP32 Keras vs INT8 TFLite
                            interpreter outputs on 32 random samples. Per the
                            Plan we want **mean KL(softmax(fp32), softmax(int8)) < 0.05**
                            (output-side KL; cache-side is monitored but not gated).

  Check 2 (X-CUBE-AI):     Run `stedgeai analyze` against the INT8 TFLite,
                            target STM32U5 (Cortex-M33 + Helium). Extract:
                            (a) whether multi-input/multi-output topology was
                            accepted (no operator errors); (b) MACs; (c) RAM /
                            ROM estimates; (d) any unsupported ops.

  Check 3 (U5 board):      Skipped — no board available on HPC. Latency is
                            extrapolated from stedgeai analyze's MACs estimate
                            using the Plan's 300 MMAC/s + 5ms/ai_run formula.

Output: prints summary + writes JSON report to `logs/tsm_probe_results.json`.
A markdown report (`tsm_probe_results.md`) is generated by a second pass.

Key design notes:
  * Probe model is **intentionally tiny** (channels 8 -> 16 -> 32, depth 2 conv
    blocks, 32x32 input — even tinier than V0). This is a SHAPE/OPS-LEVEL test:
    the point isn't accuracy, but whether the I/O topology + TSM Slice/Concat
    pattern survives quantize + stedgeai analyze.
  * Channels are chosen so n_shift = C/8 is integer at every TSM boundary
    (8 -> 1, 16 -> 2, 32 -> 4); avoids ambiguous Slice axes
  * BatchNorm folded into Conv at TFLite conversion time, ReLU as separate
    activation -- matches Plan Day 8 "Conv -> BN -> ReLU || TSM-shift" cut rule
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, Model

# Project root scripts on path
PROJECT_ROOT = Path("/leonardo_work/IscrB_WearUsFM/jzhang03/MLonMCU")
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from tsm_streaming_layer import TSMStreamingShift, causal_tsm_clip


# ---- Hyperparameters of the probe model ----
H, W = 32, 32                    # input spatial (smaller than V0 64×64 — probe only)
C_IN = 1                          # grayscale
N_DIV = 8
N_CLASSES = 27
CH = [8, 16, 32]                  # channels per stage (after each Conv-BN-ReLU)


# ---- Build streaming Keras model with multi-I/O ---------------------------

def build_streaming_probe_model() -> Model:
    """Functional model: single-frame input + two cache inputs -> logits + two cache outputs.

    Architecture (very small, just enough to exercise 2 TSM cut points):

      frame_in  [1, H, W, 1]                              ch=1
        |
        |  Conv2D(8, 3, stride=2) -> BN -> ReLU           ch=8, spatial 16x16
        |
        |  TSMStreamingShift(cache_0 in/out)               ch=8, cache shape (1,16,16,1)
        |
        |  Conv2D(16, 3, stride=2) -> BN -> ReLU          ch=16, spatial 8x8
        |
        |  TSMStreamingShift(cache_1 in/out)               ch=16, cache shape (1,8,8,2)
        |
        |  Conv2D(32, 3, stride=2) -> BN -> ReLU          ch=32, spatial 4x4
        |
        |  GlobalAveragePool                              (1, 32)
        |  Dense(27, no activation)                       (1, 27) logits
        |
      logits + cache_0_out + cache_1_out

    Cache shapes are computed at graph-build time to match TSM placement.
    """
    # Inputs
    frame_in = layers.Input(shape=(H, W, C_IN), batch_size=1, name="frame_in")
    cache_0_in = layers.Input(shape=(H // 2, W // 2, CH[0] // N_DIV), batch_size=1, name="cache_0_in")
    cache_1_in = layers.Input(shape=(H // 4, W // 4, CH[1] // N_DIV), batch_size=1, name="cache_1_in")

    # Stage 0: Conv-BN-ReLU (1 -> 8, stride 2)
    x = layers.Conv2D(CH[0], 3, strides=2, padding="same", use_bias=False, name="conv_0")(frame_in)
    x = layers.BatchNormalization(name="bn_0")(x)
    x = layers.ReLU(name="relu_0")(x)
    # TSM cut #0
    x, cache_0_out = TSMStreamingShift(n_div=N_DIV, name="tsm_0")([x, cache_0_in])

    # Stage 1: Conv-BN-ReLU (8 -> 16, stride 2)
    x = layers.Conv2D(CH[1], 3, strides=2, padding="same", use_bias=False, name="conv_1")(x)
    x = layers.BatchNormalization(name="bn_1")(x)
    x = layers.ReLU(name="relu_1")(x)
    # TSM cut #1
    x, cache_1_out = TSMStreamingShift(n_div=N_DIV, name="tsm_1")([x, cache_1_in])

    # Stage 2: Conv-BN-ReLU (16 -> 32, stride 2)
    x = layers.Conv2D(CH[2], 3, strides=2, padding="same", use_bias=False, name="conv_2")(x)
    x = layers.BatchNormalization(name="bn_2")(x)
    x = layers.ReLU(name="relu_2")(x)

    # Head: GAP + Linear
    x = layers.GlobalAveragePooling2D(name="gap")(x)
    logits = layers.Dense(N_CLASSES, name="head")(x)

    model = Model(
        inputs=[frame_in, cache_0_in, cache_1_in],
        outputs=[logits, cache_0_out, cache_1_out],
        name="streaming_probe",
    )
    return model


# ---- Sample data for representative dataset + cross-check ------------------

def make_sample_inputs(rng: np.random.Generator, batch: int = 1):
    """Return a triple (frame, cache_0, cache_1) with random uniform values
    in the [-1, 1] range (matches Pipeline L normalization).
    """
    f = rng.uniform(-1, 1, size=(batch, H, W, C_IN)).astype(np.float32)
    c0 = rng.uniform(-1, 1, size=(batch, H // 2, W // 2, CH[0] // N_DIV)).astype(np.float32)
    c1 = rng.uniform(-1, 1, size=(batch, H // 4, W // 4, CH[1] // N_DIV)).astype(np.float32)
    return f, c0, c1


def representative_dataset_factory(input_names: list[str], n_samples: int = 100, seed: int = 0):
    """Yield dict keyed by input tensor name -> avoids TFLite calibrator
    re-ordering inputs in surprising ways for multi-input models."""
    rng = np.random.default_rng(seed)
    def _gen():
        for _ in range(n_samples):
            f, c0, c1 = make_sample_inputs(rng)
            sample = {}
            for n in input_names:
                if "frame" in n:
                    sample[n] = f
                elif "cache_0" in n:
                    sample[n] = c0
                elif "cache_1" in n:
                    sample[n] = c1
                else:
                    raise KeyError(n)
            yield sample
    return _gen


# ---- Check 1: FP32 -> INT8 + interpreter cross-check -----------------------

def export_int8_tflite(model: Model, out_path: Path, saved_model_dir: Path) -> Path:
    """Post-training INT8 quantization with full integer I/O.

    Goes through SavedModel intermediate so input naming is preserved (multi-I/O
    models converted directly from_keras_model can confuse the calibrator's
    input ordering — observed empirically on TF 2.15).
    """
    if saved_model_dir.exists():
        shutil.rmtree(saved_model_dir)
    model.save(str(saved_model_dir))

    # Pick concrete function and discover input names
    converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_dir))
    # Discover input arg names by loading the saved model
    sm = tf.saved_model.load(str(saved_model_dir))
    sig = sm.signatures["serving_default"]
    input_names = list(sig.structured_input_signature[1].keys())

    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_factory(input_names, 100)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_bytes = converter.convert()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(tflite_bytes)
    return out_path


def export_fp32_tflite(model: Model, out_path: Path) -> Path:
    """FP32 TFLite (for reference / Path A.clip offline eval option)."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_bytes = converter.convert()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(tflite_bytes)
    return out_path


def run_tflite_inference(tflite_path: Path, frame: np.ndarray, cache_0: np.ndarray, cache_1: np.ndarray):
    """Run a single inference through the TFLite interpreter; handles input
    quantization (FP32 caller -> INT8 model) and output dequantization.
    Returns (logits_fp32, cache_0_out_fp32, cache_1_out_fp32).
    """
    interp = tf.lite.Interpreter(model_path=str(tflite_path))
    interp.allocate_tensors()
    input_details = interp.get_input_details()
    output_details = interp.get_output_details()

    name_to_idx = {d["name"]: d["index"] for d in input_details}

    def _find(name_part: str) -> dict:
        for d in input_details:
            if name_part in d["name"]:
                return d
        raise KeyError(name_part)

    inputs = {"frame_in": frame, "cache_0_in": cache_0, "cache_1_in": cache_1}
    for name_part, fp32_val in inputs.items():
        det = _find(name_part)
        if det["dtype"] == np.int8:
            scale, zp = det["quantization"]
            q = np.clip(np.round(fp32_val / scale + zp), -128, 127).astype(np.int8)
        else:
            q = fp32_val.astype(det["dtype"])
        interp.set_tensor(det["index"], q)

    interp.invoke()
    outs = {}
    for det in output_details:
        v = interp.get_tensor(det["index"])
        if det["dtype"] == np.int8:
            scale, zp = det["quantization"]
            v = (v.astype(np.float32) - zp) * scale
        outs[det["name"]] = v
    return outs, input_details, output_details


def kl_softmax(p_logits: np.ndarray, q_logits: np.ndarray, eps: float = 1e-9) -> float:
    """KL(softmax(p) || softmax(q)) averaged over the leading axes."""
    def _sm(x):
        x = x - x.max(axis=-1, keepdims=True)
        e = np.exp(x)
        return e / e.sum(axis=-1, keepdims=True)
    p, q = _sm(p_logits), _sm(q_logits)
    kl = (p * (np.log(p + eps) - np.log(q + eps))).sum(axis=-1)
    return float(kl.mean())


# ---- Check 2: stedgeai analyze ---------------------------------------------

def run_stedgeai_analyze(tflite_path: Path, out_dir: Path) -> dict:
    """Invoke stedgeai analyze. Returns parsed metrics dict + raw output."""
    out_dir.mkdir(parents=True, exist_ok=True)
    # Target: STM32U5 / Cortex-M33 with Helium MVE (the B-U585I-IOT02A board)
    # The "stm32" target argument is the generic STM32 MCU profile in stedgeai
    cmd = [
        "stedgeai", "analyze",
        "--model", str(tflite_path),
        "--target", "stm32",
        "--name", "streaming_probe",
        "--workspace", str(out_dir / "workspace"),
        "--output", str(out_dir / "output"),
        "--verbosity", "2",
    ]
    print(f"[probe] running: {' '.join(cmd)}", flush=True)
    t0 = time.time()
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    elapsed = time.time() - t0
    log_text = result.stdout + "\n" + result.stderr
    (out_dir / "analyze_log.txt").write_text(log_text)

    metrics = {
        "returncode": result.returncode,
        "elapsed_s": round(elapsed, 2),
        "log_path": str(out_dir / "analyze_log.txt"),
    }

    # Parse stedgeai analyze output. Format (v4.0):
    #  MACC = <int>
    #  RAM = <int> bytes
    #  ROM = <int> bytes
    #  weights = <int> bytes
    #  Number of operators kept = <int>
    # plus an "ops_unsupported" tally if any
    import re
    def _find_int(pattern: str) -> int | None:
        m = re.search(pattern, log_text, re.IGNORECASE)
        return int(m.group(1).replace(",", "")) if m else None

    macc = _find_int(r"(?:total\s+)?(?:nb\s+of\s+)?macc[\s:]+([0-9,]+)")
    ram = _find_int(r"ram[^\d]+([0-9,]+)\s*(?:bytes|b)")
    rom = _find_int(r"rom[^\d]+([0-9,]+)\s*(?:bytes|b)")
    weights = _find_int(r"weights[^\d]+([0-9,]+)\s*(?:bytes|b)")
    metrics["macc"] = macc
    metrics["ram_bytes"] = ram
    metrics["rom_bytes"] = rom
    metrics["weights_bytes"] = weights
    metrics["multi_io_accepted"] = "Operators kept" in log_text or result.returncode == 0
    metrics["log_excerpt_head"] = "\n".join(log_text.splitlines()[:20])
    metrics["log_excerpt_tail"] = "\n".join(log_text.splitlines()[-30:])

    return metrics


# ---- Top-level probe driver ------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_dir", type=Path, default=PROJECT_ROOT / "logs/tsm_probe")
    ap.add_argument("--skip_check2", action="store_true",
                    help="skip stedgeai analyze (debug only)")
    args = ap.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    # Suppress TF noise
    tf.get_logger().setLevel("ERROR")
    os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
    tf.keras.utils.set_random_seed(0)

    print("=" * 70)
    print("Day 8 TSM streaming probe — building model")
    print("=" * 70)
    model = build_streaming_probe_model()
    model.summary(print_fn=print)

    # ---- Export FP32 + INT8 TFLite ----
    fp32_path = args.out_dir / "streaming_probe_fp32.tflite"
    int8_path = args.out_dir / "streaming_probe_int8.tflite"
    print(f"\n[probe] exporting FP32 -> {fp32_path}", flush=True)
    export_fp32_tflite(model, fp32_path)
    print(f"  size = {fp32_path.stat().st_size / 1024:.1f} KB")
    print(f"\n[probe] exporting INT8 (PTQ) -> {int8_path}", flush=True)
    export_int8_tflite(model, int8_path, args.out_dir / "saved_model")
    print(f"  size = {int8_path.stat().st_size / 1024:.1f} KB")

    # ---- Check 1: FP32 Keras vs INT8 TFLite output divergence ----
    print("\n" + "=" * 70)
    print("CHECK 1 — INT8 quantization fidelity")
    print("=" * 70)
    rng = np.random.default_rng(123)
    fp32_logits_all, int8_logits_all = [], []
    cache_kls = {"cache_0": [], "cache_1": []}
    n_samples = 32
    for i in range(n_samples):
        f, c0, c1 = make_sample_inputs(rng)
        # FP32 Keras (single forward, B=1)
        out_keras = model([f, c0, c1], training=False)
        logits_keras = out_keras[0].numpy()
        # INT8 TFLite
        outs_tfl, _, _ = run_tflite_inference(int8_path, f, c0, c1)
        # outputs are named after the model output layers
        logits_int8 = None
        c0_int8 = None
        c1_int8 = None
        for name, val in outs_tfl.items():
            if "head" in name or "logits" in name:
                logits_int8 = val
            elif "tsm_0" in name:
                c0_int8 = val
            elif "tsm_1" in name:
                c1_int8 = val
        if logits_int8 is None:
            # Heuristic fallback by shape
            for name, val in outs_tfl.items():
                if val.shape[-1] == N_CLASSES:
                    logits_int8 = val
        fp32_logits_all.append(logits_keras)
        int8_logits_all.append(logits_int8)

    fp32_logits_all = np.concatenate(fp32_logits_all, axis=0)   # (n_samples, 27)
    int8_logits_all = np.concatenate(int8_logits_all, axis=0)   # (n_samples, 27)
    output_kl = kl_softmax(fp32_logits_all, int8_logits_all)
    output_kl_rev = kl_softmax(int8_logits_all, fp32_logits_all)
    output_argmax_match = (fp32_logits_all.argmax(-1) == int8_logits_all.argmax(-1)).mean()

    print(f"  samples            : {n_samples}")
    print(f"  KL(FP32 || INT8)   : {output_kl:.6f}")
    print(f"  KL(INT8 || FP32)   : {output_kl_rev:.6f}")
    print(f"  argmax agreement   : {output_argmax_match:.4f}")
    check1_pass = output_kl < 0.05
    print(f"  Check 1 verdict    : {'PASS' if check1_pass else 'FAIL'}  (gate: KL < 0.05)")

    # ---- Check 2: stedgeai analyze ----
    print("\n" + "=" * 70)
    print("CHECK 2 — stedgeai analyze (X-CUBE-AI multi-I/O + ops support)")
    print("=" * 70)
    check2 = {}
    if not args.skip_check2:
        check2 = run_stedgeai_analyze(int8_path, args.out_dir / "stedgeai")
        print(f"  stedgeai returncode  : {check2['returncode']}")
        print(f"  multi-I/O accepted   : {check2['multi_io_accepted']}")
        print(f"  MACs                 : {check2.get('macc')}")
        print(f"  RAM (bytes)          : {check2.get('ram_bytes')}")
        print(f"  ROM (bytes)          : {check2.get('rom_bytes')}")
        print(f"  weights (bytes)      : {check2.get('weights_bytes')}")
        print(f"  elapsed              : {check2['elapsed_s']}s")
        check2_pass = (check2["returncode"] == 0) and check2["multi_io_accepted"]
        print(f"  Check 2 verdict      : {'PASS' if check2_pass else 'FAIL'}")
    else:
        check2_pass = None
        print("  SKIPPED (--skip_check2)")

    # ---- Report ----
    summary = {
        "probe_model": {
            "input_HxW": [H, W],
            "input_channels": C_IN,
            "channels_per_stage": CH,
            "n_div": N_DIV,
            "n_tsm_boundaries": 2,
            "n_classes": N_CLASSES,
            "params": int(sum(int(np.prod(w.shape)) for w in model.trainable_weights)),
            "fp32_tflite_size_kb": round(fp32_path.stat().st_size / 1024, 2),
            "int8_tflite_size_kb": round(int8_path.stat().st_size / 1024, 2),
        },
        "check1_int8_fidelity": {
            "n_samples": n_samples,
            "kl_fp32_to_int8": round(output_kl, 6),
            "kl_int8_to_fp32": round(output_kl_rev, 6),
            "argmax_agreement": round(float(output_argmax_match), 4),
            "verdict": "PASS" if check1_pass else "FAIL",
            "gate": "KL(FP32||INT8) < 0.05",
        },
        "check2_stedgeai_analyze": check2 if not args.skip_check2 else {"skipped": True},
        "overall_recommendation": None,
    }

    if check1_pass and (check2_pass if not args.skip_check2 else True):
        summary["overall_recommendation"] = "Path A.streaming (default)"
    elif args.skip_check2 and check1_pass:
        summary["overall_recommendation"] = "Path A.streaming (check 1 OK; check 2 pending)"
    else:
        summary["overall_recommendation"] = "Fall back to Path B (multi-network)"

    print("\n" + "=" * 70)
    print(f"OVERALL: {summary['overall_recommendation']}")
    print("=" * 70)

    json_path = args.out_dir / "tsm_probe_results.json"
    json_path.write_text(json.dumps(summary, indent=2))
    print(f"\n[probe] wrote {json_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
